# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', models.CharField(choices=[('ROW', 'Row'), ('COLUMN', 'Column'), ('TABPANEL', 'TabPanel'), ('ACCORDION', 'Accordion'), ('RICHTEXT', 'RichText')], default='ROW', max_length=20)),
                ('content', models.CharField(max_length=250)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='cms.Page'),
        ),
    ]
